Feat/sequel compilers
Shopify/tapioca pull request #196
Opened 2020-12-27 03:30 UTC by nvh0412

### Motivation

### Implementation

### Tests

2021-01-04 14:48 UTC, Morriar requested changes
I'm not familiar with sequel but the changes look good 👍 

Can you add some tests for your compilers, like it's done for [Active Record](https://github.com/Shopify/tapioca/blob/master/spec/tapioca/compilers/dsl/active_record_columns_spec.rb) please?

Thanks for you pull-request!

2021-01-04 14:48 UTC, Morriar commented on lib/tapioca/generator.rb
> +      say("Loading Rails application and Non-Rails application")
```suggestion
      say("Loading application...")
```

2021-01-04 14:48 UTC, Morriar commented on lib/tapioca/compilers/dsl/sequel_columns.rb
> +          return ["T.untyped", "T.untyped"] if do_not_generate_strong_types?(constant)
Do you also need the `StrongTypeGeneration` pattern for sequel or is it to mirror what we do in the Active Record generators?

We might want the reverse choice, something like `UnsafeTypeGeneration` as to encourage safe typing by default.

2021-01-04 18:20 UTC, rafaelfranca commented
I don't think we should maintain Sequel compilers in tapioca. Our compilers system make it possible to people to write their own compilers, so I think a compiler to Sequel should be in its own gem, maintained by people that uses Sequel.

2021-01-05 00:23 UTC, nvh0412 commented
It makes sense, @rafaelfranca. I realized that Sequel compilers should be maintained by people that use Sequel instead of putting it into this Gem when I was implementing this stuff. Let me close this PR. Thank you, @Morriar too

2021-01-05 00:23 UTC, closed without merging