Ignore vendor folder by default
Shopify/tapioca pull request #397
Opened 2021-07-21 08:21 UTC by miry

### Motivation

There is some practices to install gems in `vendor/bundle`.
During type checking or tools around sorbet like `spoom` this line presented in each projects that I work in.

### Implementation

Generate a sorbet config with ignore vendor directive

2021-07-21 08:28 UTC, miry commented on spec/tapioca/cli/init_spec.rb
> +          --ignore=vendor
This test duplicates the code 1:1 - feel free to suggest another way.

2021-07-21 22:40 UTC, rafaelfranca requested changes
I don't think we should ignore the entire vendor folder, specially by default. `vendor` in Rails application is a place for code that belongs to the application but was copied from some vendor and could or could not be modified. `vendor/plugins` is a thing, and `vendor/assets` as well, although the later is not relevant for sorbet, but the latter is.

2021-07-23 09:44 UTC, miry commented
@rafaelfranca Good to know about other folders.

What do you think to ignore `vendor/bundle` only in this case?
If it does not also work, I am ok to close PR and keep updating config in my projects.

2021-07-26 18:36 UTC, Morriar requested changes
I don't think Tapioca should do this by default. Type-checking (or not type-checking) a specific directory seems to be an end-user decision. I would also not generate this configuration if the project does not contain a `vendor/` directory.

2021-07-27 09:12 UTC, closed without merging