Add readme directions on migrating to Tapioca
Shopify/tapioca pull request #473
Opened 2021-09-01 10:19 UTC by peternixey

### Motivation
On initially installing Tapioca I had no idea that it needed a migration in order to work from an existing Sorbet installation. This signals that need directly from the Readme

### Implementation
Updated readme

### Tests
n/a

2021-09-01 14:10 UTC, Morriar reviewed
What do you think about moving this new section right after this one: https://github.com/Shopify/tapioca/blob/8f653b36e4529b93868cf6c07d4c359aa734baee/README.md#how-does-tapioca-compare-to-srb-rbi-gems- ?

2021-09-01 23:50 UTC, Morriar requested changes
First, thanks a lot for taking care of this. Our README desperately needed some love ❤️ 

I'm not sure a hard separation between fresh Sorbet project and projects using `srb rbi` is relevant. Many sections / steps are common to both routes and we'll end up repeating a lot of content.

What do you think about merging the two approaches but marking some steps as _optional_ if they are related to `sorbet-rails` or `srb rbi`?

2021-09-01 23:50 UTC, Morriar commented on README.md
> +### Why use Tapioca
```suggestion
### Why use Tapioca?
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +Tapioca helps simplify your setup too. Gems such as `sorbet-typed`, `sorbet-rails` are ways to provide accurate typing information for DSLs and gems. However, Tapioca aims to provide the complete too
Said like that it sounds like Tapioca does not provide _accurate_ typing information contrary to other solutions?

2021-09-01 23:50 UTC, Morriar commented on README.md
> +## Installing Tapioca in a project with no existing RBI files (i.e. a fresh Sorbet project)
Let's put back the section `## How does tapioca compare to "srb rbi gems" ?` here, before jumping to the installation procedure.

2021-09-01 23:50 UTC, Morriar commented on README.md
> +### 1. Add this line to your application's `Gemfile`
```suggestion
### Add Tapioca to your application's `Gemfile`
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +### 2, Initialize folder structure
```suggestion
### Initialize the folder structure
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +### 3. Generate for gems
```suggestion
### Generate gems RBIs
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +### 4. Generate for all gems in Gemfile
```suggestion
or:
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +Command: `tapioca sync`
```suggestion
Command: `tapioca gem`
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +### 5. Generate the list of all unresolved constants
```suggestion
### Generate the list of all unresolved constants
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +### 6. Generate DSL RBI files
```suggestion
### Generate DSL RBI files
```

2021-09-01 23:50 UTC, Morriar commented on README.md
> +## Installing Tapioca into a project that already uses Sorbet (and has RBI files)
We should probably link to this page of the wiki: https://github.com/Shopify/tapioca/wiki/Migrating-to-Tapioca.

2021-09-01 23:50 UTC, Morriar commented on README.md
> +## How does tapioca compare to "srb rbi gems" ?
If we're going to document all of this here, we should also add a section explaining how to keep the RBIs up-to-date when the Gemfile changes and the files related to DSLs change.

2021-09-07 13:25 UTC, peternixey commented
Hi @Morriar - sorry for the delayed response, I was away on holiday. 

I went through your changes, all of which seemed very reasonable. I've done a complete revamp of the page here to combine the two different flows into one and then to add in the links and clarity you suggested:

https://github.com/peternixey/tapioca/blob/main/README.md

I wrote it all on the assumption that most people will find Tapioca *after* they find Sorbet and so the primary use-case is for an existing sorbet installation. You may know the reality of that better than me though! 

BTW one thing I did was compress a lot of the text down into code blocks which I think makes it easier to scan and consume - you may feel differently though. 

I also wonder whether on a document like this you might spend more time giving me kind feedback than actually doing the edits yourself. If you'd like to take the doc as it is (or as it was) and edit it however you see fit I will not be in the slightest offended and it will probably take you less time than writing me kind tweak-suggestions ;)

So let me hand this over to you and it is yours to merge / bin / use-for-inspriation as helpful!

Best wishes,
Peter

2021-09-07 23:42 UTC, rafaelfranca reviewed
While I can understand a lot of users will arive to tapioca after knowing about Sorbet I think our primary flow needs to for users that didn't setup anything yet and extract the migration "guide" to a different document linked in the README.

We can still link to the document before we explain the "pristine flow" but having both flows in the same document when users will either fall in one or another category could be confusing.

2021-09-07 23:42 UTC, rafaelfranca commented on README.md
> +````bash
```suggestion
```bash
```

2021-09-07 23:42 UTC, rafaelfranca commented on README.md
> +````
```suggestion
```
```

2021-09-07 23:42 UTC, rafaelfranca commented on README.md
> +````bash
```suggestion
```bash
```

2021-09-07 23:42 UTC, rafaelfranca commented on README.md
> +````
```suggestion
```
```

2021-09-08 06:54 UTC, peternixey commented
@rafaelfranca you guys obviously know your audience much better than me but I’m just interested in the logic as to why most people would come to Tapioca with a pristine setup.

Surely one finds out about Tapioca after trying Sorbet and then realising that it has its limitations. I could understand if Tapioca was part of the official Sorbet setup guide / package but as far as I know it’s not.

To assuage my curiosity, what’s the context in which a user would discover Tapioca prior to discovering Sorbet?

2021-09-08 08:27 UTC, peternixey commented
I’ve just realised that of course Ruby 3 uses RBI files too so presumably that would be the other (and potentially main) use case - is that right?

2021-09-08 17:45 UTC, rafaelfranca commented
Ruby 3 uses RBS files, not RBIs, so that is another migration setup.

> To assuage my curiosity, what’s the context in which a user would discover Tapioca prior to discovering Sorbet?

Inside Shopify mostly.

But my interest of moving out the migration steps is mainly because of the perspective of the library itself. As a library, Tapioca has no knowledge on your setup, so it assumes you have a pristine setup, that is the path we mostly care about. Of course how users land here will vary, and that is fine, we should document some of those cases. I just don't think having everything in the README will make it easier to read. The README should only include the pristine way. From there we can link to other pages, sometimes maintained by different people, for the various setups that people might have before arriving here.

2021-09-15 11:27 UTC, peternixey commented
Hi @rafaelfranca and thanks for your answers. I'd like to clarify what would be most helpful to you guys from this next. I

I'm getting conflicting messages from your side though so I'd prefer to either wrap up or hand it over. @Morriar had originally suggested combining the Sorbet-based installation with the pristine installation and so that's the way that I took it. 

I'm not worried if you'd prefer to leave this but if it's helpful then there's no point in wasting the few hours that I've spent revising it. If it's a hassle tell me then I'll leave it, if it's an asset then let's make the most of the couple of hours I've spent on it so far:

Can I suggest the following course of action:

1. You tell me whether or not you'd like to tweak what I've got
2. You decide whether you'd prefer to do it or you'd like me to (for small changes it's far more sensible for you to do them)
3. You decide on one person who's code reviewing so as to avoid bouncing between different points of opinion. 

FWIW I would suggest that the bulk of people outside of Shopify will find Tapioca via Sorbet so it's probably a big thing to factor into your instructions and accounting for it will hugely boost people's initial impressions of Tapioca. 

I can offer you another hour of my time but only take it if you actually want this PR otherwise let's just park it. 

Best
Peter

2021-10-14 00:43 UTC, bmulholland commented
Typo: dela -> deal

2026-06-04 21:15 UTC, closed without merging