Improve RequiresCompiler performance
Shopify/tapioca pull request #682
Opened 2021-12-27 04:28 UTC by brasic

### Motivation

When trying tapioca on a large codebase I noticed that the `require` subcommand would run for a very long time (more than 40 minutes).  When I profiled to investigate I found that almost all of time was spent running `File.basename` in a tight loop.

Looking closer, I found that most of [these calls](https://github.com/Shopify/tapioca/blob/fc1445a84a2f2287ae1c380140fb469d4ffc3a2f/lib/tapioca/compilers/requires_compiler.rb#L90) were redundant since `RequiresCompiler#name_in_project?` always receives the same `files` argument, so in all but the first call it is spending most of its time repeating previously done work.

### Implementation

I've inlined the helper method `RequiresCompiler#name_in_project?` and converted it to a set to speed up the large number of inclusion checks to be performed.  In the application I'm testing with this brings the total runtime of `tapioca require` from 40 minutes to 20 seconds.

### Tests

I believe this does not change behavior and is well covered by existing tests.  If you disagree I'm happy to add a test or benchmark of some kind.

2022-01-04 18:35 UTC, KaanOzkan approved these changes
Great find!

2022-01-05 20:48 UTC, RyanBrushett approved these changes

2022-01-06 15:59 UTC, rafaelfranca requested changes

2022-01-06 16:12 UTC, brasic commented on lib/tapioca/compilers/requires_compiler.rb
> +require "set"
TIL!  I'll convert to a true-valued hash.

2022-01-06 16:48 UTC, rafaelfranca approved these changes

2022-01-06 16:48 UTC, brasic commented
I just noticed that the CLA form is now working again, I've submitted the CLA now, can someone re-run the CLA task for me?  (I lack permission)

2022-01-06 19:31 UTC, paracycle commented on lib/tapioca/compilers/requires_compiler.rb
> +require "set"
Hmm, we have a lot of usages of `set` in Tapioca already, so I guess we would need to add it to the gemspec anyway.

2022-01-06 19:33 UTC, paracycle approved these changes

2022-01-06 19:51 UTC, merged