Make Protobuf Signature Nilable
Shopify/tapioca pull request #931
Opened 2022-05-13 15:27 UTC by RayLLiu

### Motivation

The protobuf generated ruby code should have all its attributes nilable, this PR added that behaviour so that sorbet will allow making field nil for protobuf classes.

### Implementation

### Tests

2022-05-13 20:25 UTC, slinkp requested changes
Thanks for doing this!

2022-05-13 20:25 UTC, slinkp commented on lib/tapioca/dsl/compilers/protobuf.rb
> +            return_type: "T.nilable(#{field.type})"
Assignment after instantiation works similar to return values, inconsistently with keyword args :(
 So you can _only_ assign `nil` to fields whose type is another Message type.

```ruby
[12] pry(main)> cart = Shopify::Protobuf::Cart.new
[13] pry(main)> cart.id = nil 
Google::Protobuf::TypeError: Invalid argument for string field 'id' (given NilClass).
from (pry):13:in 'method_missing'
[14] pry(main)> cart.shop_id = nil
Google::Protobuf::TypeError: Expected number type for integral field 'shop_id' (given NilClass).
from (pry):14:in 'method_missing'
19] pry(main)> cart.shipping_address = nil  # Message fields CAN be assigned nil
=> nil
[20] pry(main)> cart.shipping_address = Shopify::Protobuf::ShippingAddress.new
=> <Shopify::Protobuf::ShippingAddress: id: 0, shop_id: 0, verified: false>
[26] pry(main)> cart.shipping_address = nil  # And you can set it back to nil again
=> nil
```

2022-05-20 20:24 UTC, slinkp commented on lib/tapioca/dsl/compilers/protobuf.rb
> +                create_kw_opt_param(field.name, type: "T.nilable(#{field.init_type})", default: field.default)
Isn't that specific failure the thing that's fixed by this?
Maybe I'm misunderstanding.... example?

2022-06-21 18:13 UTC, RayLLiu commented
close as it is replaced by https://github.com/Shopify/tapioca/pull/966

2022-06-21 18:13 UTC, closed without merging